### ISSUE TITLE
cant compile program

### ISSUE THREAD

**Issue by stg11** [apurvaChaudhari/KiteCore#1]
Hello all,
I downloaded the Kite connect from github, but when I compile it , I get 162 errors. Most of the errors are in the dictionaries such as this:
//Modify an open position's product type.
var param = new Dictionary
{
["exchange"] = exchange,
["tradingsymbol"] = tradingSymbol,
["transaction_type"] = transactionType,
["position_type"] = positionType,
["quantity"] = quantity,
["old_product"] = oldProduct,
["new_product"] = newProduct
};
Error   120 Invalid initializer member declarator   

I am not able to figure out how to get it to work. Any one else have these problems?

Thanks in advance

**Comment by apurvaChaudhari** [comment]
hi,
sorry for replying so late kindly reference me next time when reporting the issue ,
kindly tell me the visual studio version u r trying to compile on and the exact errors in the seeors window

**Comment by apurvaChaudhari** [comment]
I have compiled the program on latest visual studio and its compiling fine

**Comment by stg11** [comment]
I used VS 2012, does it have to be 2015? Also, does it need .Net 4.6?
Thanks

**Comment by stg11** [comment]
I used VS 2012, does it have to be 2015? Also, does it need .Net 4.6?
Thanks

**Comment by apurvaChaudhari** [comment]
I used vs 2015 and .net 4.6

**Comment by stg11** [comment]
I used VS 2012, does it have to be 2015? Also, does it need .Net 4.6?
Thanks

**Comment by stg11** [comment]
I used VS 2012, does it have to be 2015? Also, does it need .Net 4.6?
Thanks

**Comment by stg11** [comment]
I used VS 2012, does it have to be 2015? Also, does it need .Net 4.6?
Thanks

**Comment by stg11** [comment]
I used VS 2012, does it have to be 2015? Also, does it need .Net 4.6?
Thanks

**Comment by stg11** [comment]
I used VS 2012, does it have to be 2015? Also, does it need .Net 4.6?
Thanks

**Comment by stg11** [comment]
I used VS 2012, does it have to be 2015? Also, does it need .Net 4.6?
Thanks

**Comment by stg11** [comment]
I used VS 2012, does it have to be 2015? Also, does it need .Net 4.6?
Thanks

**Comment by apurvaChaudhari** [comment]
I used vs 2015 and .net 4.6 , 
i have attached snip of project settings page below
![image](https://cloud.githubusercontent.com/assets/20776714/19199453/c83b413c-8ce1-11e6-9969-c9d493fb96d7.png)
my vs version is
![image](https://cloud.githubusercontent.com/assets/20776714/19199491/fcc281e0-8ce1-11e6-9213-66344567d24e.png)

Also add references  for 
Newtonsoft.Json 8.0.0.0
RestSharp  105.2.3.0
websocket-sharp 1.0.2.22894

try with this and let me know
