### ISSUE TITLE
KiteStream doesn't work properly.

### ISSUE THREAD

**Issue by corientdev** [apurvaChaudhari/KiteCore#3]
Hi,
Appreciate your amazing effort.
and my problem is Kitestream doesn't work properly. It basically works for the first time of your 50 loop in demo and after that it exits without exception on `this._blockingCollection.Take()` in `GetMsg()` Function at KiteStream Class.

Kindly fix.

**Comment by apurvaChaudhari** [comment]
Hi @corientdev ,
sorry for being late and please can you specify the problem more clearly. I will try to solve ASAP
thanks

**Comment by corientdev** [comment]
I will try to explain as simply as possible.

see this part of your demo code.

``` csharp
for (int i = 0; i < 50; i++)
            {
                Thread.Sleep(1000);

                //Get the decoded packets from stream these decoded packets are in form of structs
                List<dynamic> lst = stream.Getpackets();
                foreach (dynamic xLtpMode in lst)
                {
                    if (!(xLtpMode is KiteStream.LtpMode)) continue;
                    Console.WriteLine();
                    Console.WriteLine("Instrumenttocken");
                    Console.WriteLine(xLtpMode.Instrumenttocken); //4 bytes
                    Console.WriteLine("Ltp");
                    Console.WriteLine(Convert.ToDouble(xLtpMode.Ltp)/100); //4 byte
                }
            }
```

What happens is when you execute the code. It loops properly for the first time and get data from websocket. But when it loops for second time it hangs your program on this line `List<dynamic> lst = stream.Getpackets();` like deadlock and code exits from  `this._blockingCollection.Take()` line in `GetMsg()` Function at `KiteStream` Class.

I am ok to share my screen also to show you the actual issue.

**Comment by apurvaChaudhari** [comment]
It will hang if you access the stream in off market hours and if streaming in LTP mode then it will not receieve update till price changes.I tried with this 53266695(silver micro NOV future MCX) code as input to stream.SubcribeTo("53266695", "ltp"); and its looping properly.
The blocking collection blocks till new data is receieved so in off mkt hours only ltp is receieved and new data is not receieved so it blocks and waits after first iteration.
P.S in my final application I use the stream in a thread so my app does not hang

**Comment by corientdev** [comment]
Fair enough amazing library.

I have tested with GBPINR instrument code now and it works as expected. One more question. If i start the app when market is offline then what will happen i mean does it refresh itself when market opens or i need to close and restart the app again.

Appreciate your effort

**Comment by apurvaChaudhari** [comment]
In my app (the one I use to trade ) I wait for market to open before I initiate the stream, The reason being that if you stream in full mode(which i do) and keep it on in off mkt hours then it will keep sending the same data again and again till the market opens ,once mkt opens it will stream the live data.
BUT if you are using LTP or QUOTE mode then you can keep your app on before mkt hours and wen mkt opens it should start updating normally.
Note--> kite access token renews at 8.30 in morning so you will need to restart the app after 8.30AM

**Comment by corientdev** [comment]
Thank You for the help. It would be amazing if you can open source your stack in which you trade :p :dancing_men:  
I am planning to build something like algo trading (for personal use). That will be used there.

Thanks.. Keep in touch..

**Comment by apurvaChaudhari** [comment]
maby I will in the coming year 
my trading stack is just a abstraction over this library ,also external things like a storage library to store mkt data,a lib that keeps track of positions I hold  and a kind of ta-lib for using technical indicatiors(look up ta lib for .net, you can use it directly or look at the logic and develop your own).
