### ISSUE TITLE
On network connection lost, the application hangs

### ISSUE THREAD

**Issue by ghost** [apurvaChaudhari/KiteCore#5]
Hi,
I am using KiteCore in a UI application and launching KiteStream in a separate thread. The live quotes are coming fine. But on disconnecting the network when the stream is running, the application hangs after the number of retries are over. Could you please check this?
Thanks,
Ishwar.

**Comment by ghost** [comment]
Solved this using a cancellation token for the blockingCollection Take and Add calls. I will submit a hotfix for this soon.

**Comment by apurvaChaudhari** [comment]
hi,
Thanks for contributing
